### ISSUE TITLE
クイックスタートのinstall_githubリポジトリについて

### ISSUE THREAD

**Issue by akikuno** [Gedevan-Aleksizde/rmdja#2]
`rmdja`の開発と充実したドキュメントの公開を誠にありがとうございます.
[クイックスタート](https://gedevan-aleksizde.github.io/rmdja/quick-start.html)の`rmdja`のインストールについてですが, 現在リポジトリが`my_latex_template`となっています. こちらは`rmdja`でしょうか？

```
# 現在
install.packages("remotes")
remotes::install_github("Gedevan-Aleksizde/my_latex_template", 
  repos = NULL, type = "source")
```

```
# おそらくこちら？
install.packages("remotes")
remotes::install_github('Gedevan-Aleksizde/rmdja', repos = NULL)
```

**Comment by Gedevan-Aleksizde** [comment]
はい, そのとおりです. 現時点ではあまり動作確認をせずに試行錯誤しながら作っているため, ドキュメントと整合しないことが多いです.

現在は修正しました.
https://github.com/Gedevan-Aleksizde/rmdja/blob/87be0cb5c6e6d0c651d45217749b4c766d91b8ee/docs/quick-start.html
